{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-jdbc",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.2.1.jar",
          "url": "spring-boot-starter-jdbc-3.2.1.jar",
          "size": 4768,
          "sha512": "d96e52d227552c74d208a803a3c5eca6974cbcd3ab70dd0e44461752b8cc38d2478ed659a1f392d9672fd429561330e1b0826885e42aafa053d58a49a4feaf97",
          "sha256": "205814cd5fa015de5401561d7d047fff639ac20fcf8aefdf5572f8bebdb532f7",
          "sha1": "e3de1c46cd238d55f0c2a5f5ea416fadce000318",
          "md5": "99d1b027ae14beaac1f84f216647271f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.2.1.jar",
          "url": "spring-boot-starter-jdbc-3.2.1.jar",
          "size": 4768,
          "sha512": "d96e52d227552c74d208a803a3c5eca6974cbcd3ab70dd0e44461752b8cc38d2478ed659a1f392d9672fd429561330e1b0826885e42aafa053d58a49a4feaf97",
          "sha256": "205814cd5fa015de5401561d7d047fff639ac20fcf8aefdf5572f8bebdb532f7",
          "sha1": "e3de1c46cd238d55f0c2a5f5ea416fadce000318",
          "md5": "99d1b027ae14beaac1f84f216647271f"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.2.1.jar",
          "url": "spring-boot-starter-jdbc-3.2.1.jar",
          "size": 4768,
          "sha512": "d96e52d227552c74d208a803a3c5eca6974cbcd3ab70dd0e44461752b8cc38d2478ed659a1f392d9672fd429561330e1b0826885e42aafa053d58a49a4feaf97",
          "sha256": "205814cd5fa015de5401561d7d047fff639ac20fcf8aefdf5572f8bebdb532f7",
          "sha1": "e3de1c46cd238d55f0c2a5f5ea416fadce000318",
          "md5": "99d1b027ae14beaac1f84f216647271f"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-jdbc-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.2.1.jar",
          "url": "spring-boot-starter-jdbc-3.2.1.jar",
          "size": 4768,
          "sha512": "d96e52d227552c74d208a803a3c5eca6974cbcd3ab70dd0e44461752b8cc38d2478ed659a1f392d9672fd429561330e1b0826885e42aafa053d58a49a4feaf97",
          "sha256": "205814cd5fa015de5401561d7d047fff639ac20fcf8aefdf5572f8bebdb532f7",
          "sha1": "e3de1c46cd238d55f0c2a5f5ea416fadce000318",
          "md5": "99d1b027ae14beaac1f84f216647271f"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-jdbc-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.2.1-javadoc.jar",
          "url": "spring-boot-starter-jdbc-3.2.1-javadoc.jar",
          "size": 4741,
          "sha512": "9b5b1971986371ff1c52ed5afdc5b87f4b12be41be5315ceb8d215e88684ee8ebd0065e101911e1c9503a449e38c694653323bc1ac90594f702496ae80df9824",
          "sha256": "eb4dee187af865fbec4fc55b3d173ac3e2bcb71b9be0c5c1c2647dd9497e775a",
          "sha1": "487730c372e92ba7e7a81de3f108ce582d893823",
          "md5": "69e83accab831842cbfe609a4bc95a6c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.2.1-sources.jar",
          "url": "spring-boot-starter-jdbc-3.2.1-sources.jar",
          "size": 4740,
          "sha512": "987d611cf899049d0266e9d0ebc258b0c21b4975874e25117f8d7786bed6d7debd49c61ca855cb6def730cdcf359678db3bc53a10286821065a7cd0a0f64dce4",
          "sha256": "67fde824ce4ef33e7a9656be3ce033efb1d8b47608b00697430850cd3e0c7722",
          "sha1": "733df6f1c9cf1f12d61c61a6df35a30219abb91d",
          "md5": "ad6594060ff8c4a285b7daa326c8c36c"
        }
      ]
    }
  ]
}
