{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-orm",
    "version": "6.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-orm-6.1.2.jar",
          "url": "spring-orm-6.1.2.jar",
          "size": 233385,
          "sha512": "8a5cd8553172b9d5acdbce0a1ad3c9eaa2095a650d718e40f6c202d756586eadc29c390a4c935e08a30dab507aeb8a98ffd15be4d75c4a51e5fcd77fe974f371",
          "sha256": "cbb994c44c7eeebefacb34895813fd38e9ad7c986c4fe291409ea1c4fb37b280",
          "sha1": "32d93c8762b828e9017429528879d5f57be83b8f",
          "md5": "bfaf737697a6637f1f0d2376b9196a45"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-orm-6.1.2.jar",
          "url": "spring-orm-6.1.2.jar",
          "size": 233385,
          "sha512": "8a5cd8553172b9d5acdbce0a1ad3c9eaa2095a650d718e40f6c202d756586eadc29c390a4c935e08a30dab507aeb8a98ffd15be4d75c4a51e5fcd77fe974f371",
          "sha256": "cbb994c44c7eeebefacb34895813fd38e9ad7c986c4fe291409ea1c4fb37b280",
          "sha1": "32d93c8762b828e9017429528879d5f57be83b8f",
          "md5": "bfaf737697a6637f1f0d2376b9196a45"
        }
      ]
    }
  ]
}
