spring :
#  h2:
#    console:
#      enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
#      path: /h2-consol
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: 123456
#    driver-class-name: org.h2.Driver
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
#      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

