{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-aop",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-aop-3.2.1.jar",
          "url": "spring-boot-starter-aop-3.2.1.jar",
          "size": 4768,
          "sha512": "911f4f092e188c7f56bff915b6df5b8238a60efafafef275114ac32490c06bba54a22aed77906fd66bbe2e2110705336843fde23d0f9f450435e2a2916a3d8e5",
          "sha256": "d259aea58def958f35e506b083f0b7e5ae27c72404dfae95879cc40ae3fd4f10",
          "sha1": "e8daf5422a28d8b2e304a00090a8fe730bda0e6c",
          "md5": "9297f3c197307bb399c088a47a60f42b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-aop-3.2.1.jar",
          "url": "spring-boot-starter-aop-3.2.1.jar",
          "size": 4768,
          "sha512": "911f4f092e188c7f56bff915b6df5b8238a60efafafef275114ac32490c06bba54a22aed77906fd66bbe2e2110705336843fde23d0f9f450435e2a2916a3d8e5",
          "sha256": "d259aea58def958f35e506b083f0b7e5ae27c72404dfae95879cc40ae3fd4f10",
          "sha1": "e8daf5422a28d8b2e304a00090a8fe730bda0e6c",
          "md5": "9297f3c197307bb399c088a47a60f42b"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-aop-3.2.1.jar",
          "url": "spring-boot-starter-aop-3.2.1.jar",
          "size": 4768,
          "sha512": "911f4f092e188c7f56bff915b6df5b8238a60efafafef275114ac32490c06bba54a22aed77906fd66bbe2e2110705336843fde23d0f9f450435e2a2916a3d8e5",
          "sha256": "d259aea58def958f35e506b083f0b7e5ae27c72404dfae95879cc40ae3fd4f10",
          "sha1": "e8daf5422a28d8b2e304a00090a8fe730bda0e6c",
          "md5": "9297f3c197307bb399c088a47a60f42b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-aop-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-aop-3.2.1.jar",
          "url": "spring-boot-starter-aop-3.2.1.jar",
          "size": 4768,
          "sha512": "911f4f092e188c7f56bff915b6df5b8238a60efafafef275114ac32490c06bba54a22aed77906fd66bbe2e2110705336843fde23d0f9f450435e2a2916a3d8e5",
          "sha256": "d259aea58def958f35e506b083f0b7e5ae27c72404dfae95879cc40ae3fd4f10",
          "sha1": "e8daf5422a28d8b2e304a00090a8fe730bda0e6c",
          "md5": "9297f3c197307bb399c088a47a60f42b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-aop-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-aop-3.2.1-javadoc.jar",
          "url": "spring-boot-starter-aop-3.2.1-javadoc.jar",
          "size": 4740,
          "sha512": "2d58eb616df17a53a2381d2cd08339a77d8e3603aafe2c5e4e3fbd499de69a8804524f6f06bbd22c3f0a886768d1271faefbdf65c823eb15e4d5e42cdaa8b83e",
          "sha256": "d74253fccd61a83246daffa9ae0d335825d0d829682e66b1dfefe02550c68ac9",
          "sha1": "81a002229d859dd99ca9e9de7962d3ca4175fb86",
          "md5": "fee174e791fe382696b084dc199e333a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-aop-3.2.1-sources.jar",
          "url": "spring-boot-starter-aop-3.2.1-sources.jar",
          "size": 4739,
          "sha512": "78c652406566e6b5f9222d9b2b97b135267326ec8b2fa26bdc6ef05ddc480f431ac067f5559c7352860d75bd8c76115e5d68ddecb4f2774086ec863779e80cff",
          "sha256": "b8c655d67b6450f1692a3291a5890044435c5a85c0e58dbc90d755e4a8baf2d9",
          "sha1": "f09b6dc5ebd46532cbde7659eaf2e0a331a0b817",
          "md5": "2e0cde09324216ac34a347299fb41b0d"
        }
      ]
    }
  ]
}
