{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-aspects",
    "version": "6.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aspects-6.1.2.jar",
          "url": "spring-aspects-6.1.2.jar",
          "size": 49824,
          "sha512": "f3afd11a35a5d8cb4d7a67fcbe22a31072cc4e38a820db0b0ef314f4c1c4f3aa28e9f9b7db1d4f2d677775c741450716856ae8c6700a71282b2eddc3fc605cb9",
          "sha256": "ef6b7645157e9f080d0d708773acd0183fe2be62b3d759b037d9199b065a6d2f",
          "sha1": "423247e0be90804888668ea16d7e7f0d9168a7b9",
          "md5": "0afb71c6ac50e2222ff10dc4ef904823"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aspects-6.1.2.jar",
          "url": "spring-aspects-6.1.2.jar",
          "size": 49824,
          "sha512": "f3afd11a35a5d8cb4d7a67fcbe22a31072cc4e38a820db0b0ef314f4c1c4f3aa28e9f9b7db1d4f2d677775c741450716856ae8c6700a71282b2eddc3fc605cb9",
          "sha256": "ef6b7645157e9f080d0d708773acd0183fe2be62b3d759b037d9199b065a6d2f",
          "sha1": "423247e0be90804888668ea16d7e7f0d9168a7b9",
          "md5": "0afb71c6ac50e2222ff10dc4ef904823"
        }
      ]
    }
  ]
}
