{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-jdbc",
    "version": "6.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-jdbc-6.1.2.jar",
          "url": "spring-jdbc-6.1.2.jar",
          "size": 460445,
          "sha512": "3f0aaff57963524a719db8621934ee206554ba80f21bb161415ed403ed8274b429090637a01737b069db015f4285507278bb970becd1b4c0777460fb7216f48e",
          "sha256": "3627b743d949a198caa34975e2577ce61092c2adac406170c968414464bff9e4",
          "sha1": "2c9b37e4cc9bfd7e413d4685f09b6c5447d75638",
          "md5": "529d6429f2540d0fd27af7c06213b880"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-jdbc-6.1.2.jar",
          "url": "spring-jdbc-6.1.2.jar",
          "size": 460445,
          "sha512": "3f0aaff57963524a719db8621934ee206554ba80f21bb161415ed403ed8274b429090637a01737b069db015f4285507278bb970becd1b4c0777460fb7216f48e",
          "sha256": "3627b743d949a198caa34975e2577ce61092c2adac406170c968414464bff9e4",
          "sha1": "2c9b37e4cc9bfd7e413d4685f09b6c5447d75638",
          "md5": "529d6429f2540d0fd27af7c06213b880"
        }
      ]
    }
  ]
}
