{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-jpa",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.4.1.Final"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.2.1.jar",
          "url": "spring-boot-starter-data-jpa-3.2.1.jar",
          "size": 4760,
          "sha512": "35147eccce8b89eed6c2a99248368ff6e5c1c5195238f700ecd5c2b3270b6035fff1046d0cf0680cc834afdf0bd68449c11926a195e9dd3a96789d0cdd17d287",
          "sha256": "bc12d32c1015c772927c879783b192cc7b7e4e0b3afee19fc64cb0ff1a2d3791",
          "sha1": "3d48124f433375cf0113aa69603021635b55a21a",
          "md5": "318cdbb07e5a669e5954cd14fea54a75"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.4.1.Final"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.2.1.jar",
          "url": "spring-boot-starter-data-jpa-3.2.1.jar",
          "size": 4760,
          "sha512": "35147eccce8b89eed6c2a99248368ff6e5c1c5195238f700ecd5c2b3270b6035fff1046d0cf0680cc834afdf0bd68449c11926a195e9dd3a96789d0cdd17d287",
          "sha256": "bc12d32c1015c772927c879783b192cc7b7e4e0b3afee19fc64cb0ff1a2d3791",
          "sha1": "3d48124f433375cf0113aa69603021635b55a21a",
          "md5": "318cdbb07e5a669e5954cd14fea54a75"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.2.1.jar",
          "url": "spring-boot-starter-data-jpa-3.2.1.jar",
          "size": 4760,
          "sha512": "35147eccce8b89eed6c2a99248368ff6e5c1c5195238f700ecd5c2b3270b6035fff1046d0cf0680cc834afdf0bd68449c11926a195e9dd3a96789d0cdd17d287",
          "sha256": "bc12d32c1015c772927c879783b192cc7b7e4e0b3afee19fc64cb0ff1a2d3791",
          "sha1": "3d48124f433375cf0113aa69603021635b55a21a",
          "md5": "318cdbb07e5a669e5954cd14fea54a75"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.2.1.jar",
          "url": "spring-boot-starter-data-jpa-3.2.1.jar",
          "size": 4760,
          "sha512": "35147eccce8b89eed6c2a99248368ff6e5c1c5195238f700ecd5c2b3270b6035fff1046d0cf0680cc834afdf0bd68449c11926a195e9dd3a96789d0cdd17d287",
          "sha256": "bc12d32c1015c772927c879783b192cc7b7e4e0b3afee19fc64cb0ff1a2d3791",
          "sha1": "3d48124f433375cf0113aa69603021635b55a21a",
          "md5": "318cdbb07e5a669e5954cd14fea54a75"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.2.1-javadoc.jar",
          "url": "spring-boot-starter-data-jpa-3.2.1-javadoc.jar",
          "size": 4746,
          "sha512": "007826b6c8ef5cd9e46c5aecb329161599bfbc5e94c9ce0413b8e23538560b0694c3bbe10f6e978fb5326520fd2675b16c9a4fc41e05e7e54f0595b4ede32735",
          "sha256": "f88b7d74a41fd3c637cf84b142ee0adcd4f072c6b5c5aa41f2e9d4dd2ec7369c",
          "sha1": "119b0561b5de3f83f1afbd30e9687458c498f789",
          "md5": "896c38db56de114ccc692406bb0eeded"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.2.1-sources.jar",
          "url": "spring-boot-starter-data-jpa-3.2.1-sources.jar",
          "size": 4745,
          "sha512": "a134f9d747c7af4a38cbc212e3babe3538b60d1aaceead4ff3a8eb32fef65dc7b2a5adf64bcdd66bbfb18615da8d5e363f51cadd54e733d1697264ae0ede9467",
          "sha256": "4073e6e855cf6ba13d1dcebda170a90b5508b4077c71284cfd86053441663df5",
          "sha1": "e183e6b4e7a229c5dbc1e16c6040c3e6d8a9f159",
          "md5": "db17b05ff17b2fd043acd406f02c64e9"
        }
      ]
    }
  ]
}
