{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-devtools",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-devtools-3.2.1.jar",
          "url": "spring-boot-devtools-3.2.1.jar",
          "size": 203110,
          "sha512": "ec4e40093f402bbfd751ffc053d4e4aa5df3034d1b47a3b5a4d37d760e8ea351da12a5df3b5f0ebfe37bad5c0d24df1e9fe6fdc73f4a2a55f0116ea27934a348",
          "sha256": "74db481db32454a64c72ecf2ca58802aca95068ed483441d38635658df15ac25",
          "sha1": "6c725582be436b834450dffb0e158c3276f0183e",
          "md5": "38b8cdd0a6ba154b70f0958a09e1b163"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-devtools-3.2.1.jar",
          "url": "spring-boot-devtools-3.2.1.jar",
          "size": 203110,
          "sha512": "ec4e40093f402bbfd751ffc053d4e4aa5df3034d1b47a3b5a4d37d760e8ea351da12a5df3b5f0ebfe37bad5c0d24df1e9fe6fdc73f4a2a55f0116ea27934a348",
          "sha256": "74db481db32454a64c72ecf2ca58802aca95068ed483441d38635658df15ac25",
          "sha1": "6c725582be436b834450dffb0e158c3276f0183e",
          "md5": "38b8cdd0a6ba154b70f0958a09e1b163"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-devtools-3.2.1.jar",
          "url": "spring-boot-devtools-3.2.1.jar",
          "size": 203110,
          "sha512": "ec4e40093f402bbfd751ffc053d4e4aa5df3034d1b47a3b5a4d37d760e8ea351da12a5df3b5f0ebfe37bad5c0d24df1e9fe6fdc73f4a2a55f0116ea27934a348",
          "sha256": "74db481db32454a64c72ecf2ca58802aca95068ed483441d38635658df15ac25",
          "sha1": "6c725582be436b834450dffb0e158c3276f0183e",
          "md5": "38b8cdd0a6ba154b70f0958a09e1b163"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-devtools-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-devtools-3.2.1.jar",
          "url": "spring-boot-devtools-3.2.1.jar",
          "size": 203110,
          "sha512": "ec4e40093f402bbfd751ffc053d4e4aa5df3034d1b47a3b5a4d37d760e8ea351da12a5df3b5f0ebfe37bad5c0d24df1e9fe6fdc73f4a2a55f0116ea27934a348",
          "sha256": "74db481db32454a64c72ecf2ca58802aca95068ed483441d38635658df15ac25",
          "sha1": "6c725582be436b834450dffb0e158c3276f0183e",
          "md5": "38b8cdd0a6ba154b70f0958a09e1b163"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-devtools-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-devtools-3.2.1-javadoc.jar",
          "url": "spring-boot-devtools-3.2.1-javadoc.jar",
          "size": 346249,
          "sha512": "d95f887cf321eaca97fd8e9def305b83b1e39339a9f5dca5cab172f9867cc703f6fc90c1bc8ed394d29b6ee75ca8bb94a25969d2e01829355e26e7bec4b021f9",
          "sha256": "dc9b8f9616a3ef4f419a4213c21cc2bb458dc9aab38d3c5143200c7428b00b97",
          "sha1": "5f5ed8d95f5a337d98c75418250859c5fb775bb2",
          "md5": "573fbc2949cd96a438a4cc82c8e73ebd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-devtools-3.2.1-sources.jar",
          "url": "spring-boot-devtools-3.2.1-sources.jar",
          "size": 139027,
          "sha512": "3fec2160c28ebca89fa55d46e565548864b02eecb7d8ab79a240f404c023b592f2656a8b1980328caced621068718e9eac6917dd19178fa742696e6710de0cdc",
          "sha256": "d06e87eebc821c74e0d286aadd4b043d1419cebc4d1f2d77199a3292ca24de80",
          "sha1": "71bdcdde9edcbbe048f3a4cb3819ec57be202356",
          "md5": "9877a16035b75150d14705ab67246469"
        }
      ]
    }
  ]
}
